# Generated by Django 4.2.5 on 2024-01-06 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="made_recipes",
        ),
        migrations.RemoveField(
            model_name="dashboard",
            name="saved_recipes",
        ),
    ]
