# Generated by Django 4.2.5 on 2024-01-29 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="liked_by",
            new_name="user",
        ),
    ]
