# Generated by Django 4.2.5 on 2023-09-19 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0002_recipe_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="saved_recipes",
            field=models.ManyToManyField(
                related_name="saved_recipe", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
