# Generated by Django 4.2.5 on 2023-09-22 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0003_recipe_saved_recipes"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="made_recipes",
            field=models.ManyToManyField(
                related_name="made_recipe", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
