# Generated by Django 4.2.5 on 2024-01-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_alter_maderecipe_options_alter_savedrecipe_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_recipes",
                to="recipes.recipe",
            ),
        ),
    ]
