# Generated by Django 4.2.5 on 2024-02-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_savedrecipe_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/recipes"),
        ),
    ]
