# Generated by Django 4.2.5 on 2024-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
