# Generated by Django 4.2.5 on 2023-09-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Notification Categories",
            },
        ),
        migrations.RemoveField(
            model_name="notification",
            name="name",
        ),
        migrations.AddField(
            model_name="notification",
            name="description",
            field=models.CharField(default="test description", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.notificationcategory",
            ),
            preserve_default=False,
        ),
    ]
