# Generated by Django 4.2.5 on 2024-01-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0002_notificationcategory_remove_notification_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("badge awarded", "Badge Awarded")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="NotificationCategory",
        ),
    ]
