# Generated by Django 4.2.5 on 2024-01-13 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0002_alter_badge_badge_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badgecategory",
            options={"verbose_name_plural": "Badge Categories"},
        ),
    ]
