# Generated by Django 4.2.5 on 2024-01-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0003_alter_badgecategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="points_required",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
