# Generated by Django 4.2.5 on 2024-01-13 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("badges", "0004_badge_points_required"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="awardedbadge",
            unique_together={("badge", "awarded_to")},
        ),
    ]
