# Generated by Django 4.2.5 on 2024-02-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0005_alter_awardedbadge_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="displayed",
            field=models.BooleanField(default=False),
        ),
    ]
