# Generated by Django 4.2.5 on 2024-02-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0006_badge_displayed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="displayed",
        ),
        migrations.AddField(
            model_name="awardedbadge",
            name="displayed",
            field=models.BooleanField(default=False),
        ),
    ]
